<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

class CreateFormAnswersTable extends Migration
{

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('form_answers', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('parent_id');
            $table->text('answer001');
            $table->text('answer002');
            $table->text('answer003');
            $table->text('answer004');
            $table->text('answer005');
            $table->text('answer006');
            $table->text('answer007');
            $table->text('answer008');
            $table->text('answer009');
            $table->text('answer010');
            $table->text('answer011');
            $table->text('answer012');
            $table->text('answer013');
            $table->text('answer014');
            $table->text('answer015');
            $table->text('answer016');
            $table->text('answer017');
            $table->text('answer018');
            $table->text('answer019');
            $table->text('answer020');
            $table->text('answer021');
            $table->text('answer022');
            $table->text('answer023');
            $table->text('answer024');
            $table->text('answer025');
            $table->text('answer026');
            $table->text('answer027');
            $table->text('answer028');
            $table->text('answer029');
            $table->text('answer030');
            $table->text('answer031');
            $table->text('answer032');
            $table->text('answer033');
            $table->text('answer034');
            $table->text('answer035');
            $table->text('answer036');
            $table->text('answer037');
            $table->text('answer038');
            $table->text('answer039');
            $table->text('answer040');
            $table->text('answer041');
            $table->text('answer042');
            $table->text('answer043');
            $table->text('answer044');
            $table->text('answer045');
            $table->text('answer046');
            $table->text('answer047');
            $table->text('answer048');
            $table->text('answer049');
            $table->text('answer050');
            $table->text('answer051');
            $table->text('answer052');
            $table->text('answer053');
            $table->text('answer054');
            $table->text('answer055');
            $table->text('answer056');
            $table->text('answer057');
            $table->text('answer058');
            $table->text('answer059');
            $table->text('answer060');
            $table->text('answer061');
            $table->text('answer062');
            $table->text('answer063');
            $table->text('answer064');
            $table->text('answer065');
            $table->text('answer066');
            $table->text('answer067');
            $table->text('answer068');
            $table->text('answer069');
            $table->text('answer070');
            $table->text('answer071');
            $table->text('answer072');
            $table->text('answer073');
            $table->text('answer074');
            $table->text('answer075');
            $table->text('answer076');
            $table->text('answer077');
            $table->text('answer078');
            $table->text('answer079');
            $table->text('answer080');
            $table->text('answer081');
            $table->text('answer082');
            $table->text('answer083');
            $table->text('answer084');
            $table->text('answer085');
            $table->text('answer086');
            $table->text('answer087');
            $table->text('answer088');
            $table->text('answer089');
            $table->text('answer090');
            $table->text('answer091');
            $table->text('answer092');
            $table->text('answer093');
            $table->text('answer094');
            $table->text('answer095');
            $table->text('answer096');
            $table->text('answer097');
            $table->text('answer098');
            $table->text('answer099');
            $table->text('answer100');
            $table->text('answer101');
            $table->text('answer102');
            $table->text('answer103');
            $table->text('answer104');
            $table->text('answer105');
            $table->text('answer106');
            $table->text('answer107');
            $table->text('answer108');
            $table->text('answer109');
            $table->text('answer110');
            $table->text('answer111');
            $table->text('answer112');
            $table->text('answer113');
            $table->text('answer114');
            $table->text('answer115');
            $table->text('answer116');
            $table->text('answer117');
            $table->text('answer118');
            $table->text('answer119');
            $table->text('answer120');
            $table->text('answer121');
            $table->text('answer122');
            $table->text('answer123');
            $table->text('answer124');
            $table->text('answer125');
            $table->text('answer126');
            $table->text('answer127');
            $table->text('answer128');
            $table->text('answer129');
            $table->text('answer130');
            $table->text('answer131');
            $table->text('answer132');
            $table->text('answer133');
            $table->text('answer134');
            $table->text('answer135');
            $table->text('answer136');
            $table->text('answer137');
            $table->text('answer138');
            $table->text('answer139');
            $table->text('answer140');
            $table->text('answer141');
            $table->text('answer142');
            $table->text('answer143');
            $table->text('answer144');
            $table->text('answer145');
            $table->text('answer146');
            $table->text('answer147');
            $table->text('answer148');
            $table->text('answer149');
            $table->text('answer150');
            $table->text('conversion_param');
            $table->text('ip_address');
            $table->text('user_agent');
            $table->integer('created_id')->default(1);
            $table->integer('updated_id')->default(1);
            $table->timestamps();
            $table->softDeletes();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('form_answers');
    }
}
